In [1]:
import pandas as pd
import numpy as np
import os

In [4]:
files = os.listdir()
for i, v in enumerate(files):
    print(i, v)

0 38_sick_train.csv
1 38_sick_test.csv
2 Untitled.ipynb
3 .ipynb_checkpoints
4 MATH_BIOINF_547__DARPA_Data_README.pdf

In [12]:
train = pd.read_csv('38_sick_test.csv')
print("Dimensions: {}".format(train.shape))
print("Columns: {}".format(', '.join(train.columns)))
train.head()

Dimensions: (754, 31)
Columns: d3mIndex, age, sex, on_thyroxine, query_on_thyroxine, on_antithyroid_medication, sick, pregnant, thyroid_surgery, I131_treatment, query_hypothyroid, query_hyperthyroid, lithium, goitre, tumor, hypopituitary, psych, TSH_measured, TSH, T3_measured, T3, TT4_measured, TT4, T4U_measured, T4U, FTI_measured, FTI, TBG_measured, TBG, referral_source, Class

,d3mIndex,age,sex,on_thyroxine,query_on_thyroxine,on_antithyroid_medication,sick,pregnant,thyroid_surgery,I131_treatment,...,TT4_measured,TT4,T4U_measured,T4U,FTI_measured,FTI,TBG_measured,TBG,referral_source,Class
0,1,23.0,F,f,f,f,f,f,f,f,...,t,102.0,f,NaN,f,NaN,f,NaN,other,NaN
1,4,70.0,F,f,f,f,f,f,f,f,...,t,61.0,t,0.87,t,70.0,f,NaN,SVI,NaN
2,7,80.0,F,f,f,f,f,f,f,f,...,t,80.0,t,0.70,t,115.0,f,NaN,SVI,NaN
3,12,71.0,F,f,f,f,t,f,f,f,...,t,171.0,t,1.13,t,151.0,f,NaN,other,NaN
4,17,63.0,F,f,f,f,f,f,f,f,...,t,117.0,t,0.96,t,121.0,f,NaN,SVI,NaN

In [17]:
# Since column 'd3mIndex' can vbe ignored, drop 
train.drop(columns=['d3mIndex'], axis=1, inplace=True)

In [19]:
train['sick']

0      f
1      f
2      f
3      t
4      f
5      f
6      f
7      f
8      f
9      f
10     f
11     f
12     f
13     t
14     f
15     f
16     f
17     f
18     f
19     f
20     f
21     f
22     f
23     f
24     f
25     f
26     f
27     f
28     f
29     f
      ..
724    f
725    f
726    f
727    f
728    f
729    f
730    f
731    f
732    f
733    f
734    f
735    f
736    f
737    f
738    f
739    f
740    f
741    f
742    f
743    f
744    f
745    f
746    f
747    f
748    f
749    f
750    f
751    f
752    f
753    f
Name: sick, Length: 754, dtype: object